### ISSUE TITLE
2.1 Access Module Class Diagram

### ISSUE THREAD

**Issue by perrymatthew** [perrymatthew/cos301_team_ruby#20]

**Comment by vtwigge1000** [comment]
I know the User interacts with the Access Channel in an abstract manner via Android, iOS, Web etc. So at the moment the diagram shows the abstract interaction between User and Access Channel, but I'm not sure if it should rather show the physical interaction (first via the three platforms) instead of the abstract interaction? What do you think?

**Comment by perrymatthew** [comment]
Have the User interact with the abstract channel, the iOS, Android and WebUI can all extend the Abstract interface. think that'll work?

**Comment by vtwigge1000** [comment]
Yes that sounds right.
