### ISSUE TITLE
4.6 Fitness Use Case Diagram

### ISSUE THREAD

**Issue by PhutiSetoaba** [perrymatthew/cos301_team_ruby#22]

**Comment by kgothatsotlaka** [comment]
I checked the use case diagram. It looks nicely simplified, but here's a few things I thought as I was going through it

1.  The Input Goal use case

-  I think if you can have some Data store where all the data will be stored and persisted

2. With The View Goal use case
- The user will be accessing this data from the data store so it will be nice if you can show the relation between the data store and the this use case

3. View Number of steps will also need to have a relationship with the data store

lastly it is always a good idea to number your use cases, this comes in handy when you are doing a tracebility matrix

**Comment by PhutiSetoaba** [comment]
Okay thank you. Mind telling me what exactly you mean by a data store. Would the data store have to be another actor or should I just mention it as a "server" within the use case block?

**Comment by kgothatsotlaka** [comment]
Its a  actor receiving output data from a usecase


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: PhutiSetoaba <notifications@github.com> Date: 2017/03/08  20:59  (GMT+02:00) To: perrymatthew/cos301_team_ruby <cos301_team_ruby@noreply.github.com> Cc: Mankgwanyane Tlaka <u14351872@tuks.co.za>, Comment <comment@noreply.github.com> Subject: Re: [perrymatthew/cos301_team_ruby] 4.6 Fitness Use Case Diagram (#22) 
Okay thank you. Mind telling me what exactly you mean by a data store. Would the data store have to be another actor or should I just mention it as a "server" within the use case block?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/perrymatthew/cos301_team_ruby","title":"perrymatthew/cos301_team_ruby","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/perrymatthew/cos301_team_ruby"}},"updates":{"snippets":[{"icon":"PERSON","message":"@PhutiSetoaba in #22: Okay thank you. Mind telling me what exactly you mean by a data store. Would the data store have to be another actor or should I just mention it as a \"server\" within the use case block?"}],"action":{"name":"View Issue","url":"https://github.com/perrymatthew/cos301_team_ruby/issues/22#issuecomment-285134411"}}}
-- 
This message and attachments are subject to a disclaimer. Please refer to 
http://www.it.up.ac.za/documentation/governance/disclaimer/ for full 
details.
